### PR TITLE
Update to support new Codelib scheme

### LINKED ISSUE #1: Update to support new Codelib scheme
As of Project-ARTist/ARTist#2, we have a slightly different codelib format. Hence, the codelib-gen tool needs to be adapted accordingly.

### PR DESCRIPTION
**Pull request by alfink**
fixes #1

### CODE REVIEW

**Review by schrnz — CHANGES_REQUESTED** [review]
Triggers the following error for me:

```
CodeLibGen (1.0.0 RC2) Python Version: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
Generating codelib sources for: ../../modules/template-module/codelib.apk
Traceback (most recent call last):
  File "./codelib-gen.py", line 485, in <module>
    main(args)
  File "./codelib-gen.py", line 451, in main
    codelib_generator.Run()
  File "./codelib-gen.py", line 369, in Run
    compilation_unit = javalang.parse.parse(codelib_source_file.read())
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 14: invalid start byte
```

**Comment by alfink** [comment]
I assume the problem is that you provide an apk instead of an .java file

**Comment by schrnz** [comment]
Also, if you make non-trivial changes (which is obviously the case here), add yourself to the author list of the files you changed (in the header AND in the code)

**Comment by schrnz** [comment]
Also the usage guide in the README needs to be updated =)

**Comment by schrnz** [comment]
My apologies, I totally missed that I provided an apk... the generation works fine if you provide the Java file :+1:

**Review by schrnz — APPROVED** [review]

**Pull request merged**
